version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    env_file:
      - ./.env
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SSL_ENABLED=${SSL_ENABLED:-false}
      - SSL_CERT_PATH=${SSL_CERT_PATH:-/etc/nginx/ssl/cert.pem}
      - SSL_KEY_PATH=${SSL_KEY_PATH:-/etc/nginx/ssl/key.pem}
    volumes:
      - ./nginx-http.conf:/etc/nginx/nginx-http.conf:ro
      - ./nginx-ssl.conf:/etc/nginx/nginx-ssl.conf:ro
      - ./nginx-entrypoint.sh:/docker-entrypoint.sh:ro
      - ${SSL_CERT_DIR:-./ssl}:/etc/nginx/ssl:ro
    command: ["/docker-entrypoint.sh"]
    depends_on:
      - backend
      - frontend

volumes:
  backend_data:
