version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    env_file:
      - ./.env
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  backend_data:
